### ISSUE TITLE
People cant join server sometimes, after they try serveral times they suddenly are able to join.

### ISSUE THREAD

**Issue by s0ig** [ESX-Org/esx_whitelist#4]
For most  people whitelist works, but for some reason some ppl are not able to join server so easily they  have to spam connect button many times before it works.  I always delete cache and restart server after i add new players to whitelist.

**Comment by RomainLanz** [comment]
Hey @s0ig ! 👋 

How are you adding people to your whitelist?

**Comment by shdjahdk** [comment]
Yeah how are you adding people to the whitelist?
