### ISSUE TITLE
How to add players to whitelisting?

### ISSUE THREAD

**Issue by FyveFourOh** [ESX-Org/esx_whitelist#5]
Hi! I can't seem to figure out how to exactly whitelist someone, including myself. I have been looking through the files but I am dumb. Could you maybe give me the command? I really appreciate you for taking the time to answer my question!

**Comment by shdjahdk** [comment]
I would like to figger it out too

**Comment by sesipod** [comment]
@FyveFourOh 
@shdjahdk 

Like so:

![121](https://user-images.githubusercontent.com/1533744/43335030-368c8e80-9194-11e8-9c7e-e0c1982ce067.JPG)

**Comment by ThomasGH5** [comment]
@sesipod 
Hello! I don't understand how to do that. Is this an application to install, or is it something online? Please guide me through it, as the file doesn't come with any hints on how to do it. 
Thanks.

**Comment by DoingBa** [comment]
This added the username to the table, but when trying to connect to the server it still says they'r not whitelisted.

**Comment by Bignutta** [comment]
Iv been stressing for days trying to look for this help. And it helped me. Thanks dude.
